/**
 * Copyright (c) Statsify
 *
 * This source code is licensed under the GNU GPL v3 license found in the
 * LICENSE file in the root directory of this source tree.
 * https://github.com/Statsify/statsify/blob/main/LICENSE
 */

import { Background } from "~/components/background";
import { Navbar } from "~/components/navbar";
import { Search } from "~/components/search";
import type { Metadata } from "next";
import type { PropsWithChildren } from "react";

export const metadata: Metadata = {
	title: "Statsify",
	description: "Generated by create next app",
};

export default function Layout({ children }: PropsWithChildren) {
	return (
		<>
			<Background />
			<Navbar>
				<Search className="w-full md:absolute md:top-10 md:w-1/4 lg:w-1/3" />
			</Navbar>
			<main className="flex w-full grow flex-col items-center justify-center md:pt-16">{children}</main>
		</>
	);
}
