/**
 * Copyright (c) Statsify
 *
 * This source code is licensed under the GNU GPL v3 license found in the
 * LICENSE file in the root directory of this source tree.
 * https://github.com/Statsify/statsify/blob/main/LICENSE
 */

// @generated — do NOT edit manually.
// Run `pnpm scripts quests:regen` to regenerate from the live Hypixel resource.
// Shape: { [hypixelQuestId]: { [objectiveId]: target } }

export const QUEST_OBJECTIVE_TARGETS: Record<string, Record<string, number>> = {
  arcade_gamer: { play: 3 },
  arcade_specialist: { play: 20 },
  arcade_winner: { win: 1 },
  arena_daily_kills: { arena_daily_kills: 5 },
  arena_daily_play: { arena_daily_play: 5 },
  arena_daily_wins: { arena_daily_wins: 2 },
  arena_weekly_play: { arena_weekly_play: 35 },
  bedwars_daily_bed_breaker: { bedwars_weekly_final_killer: 3 },
  bedwars_daily_final_killer: { bedwars_daily_final_killer: 15 },
  bedwars_daily_one_more: { bedwars_daily_played: 3 },
  bedwars_daily_win: { bedwars_daily_win: 1 },
  bedwars_weekly_bed_elims: { bedwars_bed_elims: 25 },
  bedwars_weekly_challenges_win: { bedwars_weekly_challenge_wins: 5 },
  bedwars_weekly_dream_win: { bedwars_dream_wins: 10 },
  bedwars_weekly_final_killer: { bedwars_weekly_final_killer: 150 },
  blitz_game_of_the_day: {},
  blitz_kills: { killblitz10: 5 },
  blitz_loot_chest_daily: { lootchestblitz: 25 },
  blitz_loot_chest_weekly: { lootchestblitz: 100, dealdamageblitz: 250 },
  blitz_weekly_master: { blitz_games_played: 15, winblitz: 5, killblitz10: 30 },
  blitz_win: {},
  build_battle_player: { play: 3 },
  build_battle_weekly: { play: 30 },
  build_battle_winner: { win: 1 },
  crazy_walls_daily_kill: { crazy_walls_daily_kill: 10 },
  crazy_walls_daily_play: { crazy_walls_daily_play: 2 },
  crazy_walls_daily_win: { crazy_walls_daily_win: 1 },
  crazy_walls_weekly: { crazy_walls_weekly_play: 30 },
  cvc_kill: { cvc_kill_daily_deathmatch: 300 },
  cvc_kill_daily_normal: { cvc_kill_daily_normal: 15 },
  cvc_kill_weekly: { cvc_play_weekly: 100, cvc_play_weekly_2: 1500, cvc_play_weekly_3: 20 },
  cvc_play_daily_gungame: { cvc_play_daily_gungame: 3 },
  cvc_win_daily_deathmatch: { cvc_play_daily_deathmatch: 1 },
  cvc_win_daily_normal: { cvc_play_daily_normal: 1 },
  duels_killer: { kill: 5 },
  duels_player: { play: 5 },
  duels_weekly_kills: { kill: 100 },
  duels_weekly_wins: { win: 50 },
  duels_winner: { win: 1 },
  gingerbread_bling_bling: { gingerbread_gold_pickedup: 50 },
  gingerbread_maps: { gingerbread_races_completed: 5 },
  gingerbread_mastery: { gingerbread_races_completed: 35 },
  gingerbread_racer: { gingerbread_laps_completed: 5 },
  mega_walls_aggressor: { mega_walls_wither_damage_daily: 500 },
  mega_walls_defender: { mega_walls_kill_daily: 10 },
  mega_walls_faithful: { mega_walls_faithful_play: 3, mega_walls_faifthful_win: 1 },
  mega_walls_kill: { mega_walls_kill_daily: 15 },
  mega_walls_play: { mega_walls_play: 1 },
  mega_walls_teamwork: { mega_walls_wither_damage_weekly: 1500, mega_walls_kill_weekly: 50 },
  mega_walls_weekly: { mega_walls_play_weekly: 15, mega_walls_kill_weekly: 25 },
  mega_walls_win: { mega_walls_win: 1 },
  mm_daily_infector: { mm_infection_kills: 10 },
  mm_daily_power_play: { mm_power_play: 1 },
  mm_daily_target_kill: { mm_target_kills: 2 },
  mm_daily_win: { mm_daily_win: 1 },
  mm_weekly_murderer_kills: { mm_weekly_kills_as_murderer: 40 },
  mm_weekly_wins: { mm_weekly_win: 15 },
  paintball_expert: { kill: 750, play: 30 },
  paintball_killer: { kill: 100 },
  paintballer: { win: 1 },
  pit_daily_contract: { pit_daily_contract: 1 },
  pit_daily_kills: { kill: 25 },
  pit_weekly_gold: { pit_weekly_gold: 10_000 },
  quake_daily_kill: { quake_daily_kill: 50 },
  quake_daily_play: { quake_daily_play: 3 },
  quake_daily_win: { quake_daily_win: 1 },
  quake_weekly_play: { quake_weekly_play: 20, quake_weekly_streak: 10 },
  skyclash_kills: { kill: 15 },
  skyclash_play_games: { play: 5 },
  skyclash_play_points: { skyclash_play_points: 24 },
  skyclash_void: { skyclash_void_kills: 5, skyclash_enderchests: 3 },
  skyclash_weekly_kills: { kill: 150 },
  skywars_arcade_win: { skywars_arcade_win: 1 },
  skywars_daily_mega_kills: { skywars_mega_daily_kills: 5 },
  skywars_daily_mini_win: { skywars_mini_daily_win: 1 },
  skywars_monthly_earn_opals: { skywars_earn_opals: 1 },
  skywars_solo_win: { skywars_solo_win: 1 },
  skywars_team_win: { skywars_team_win: 1 },
  skywars_weekly_kills: { skywars_weekly_kills: 150 },
  skywars_weekly_wins: { skywars_weekly_wins: 15 },
  solo_brawler: {},
  supersmash_solo_kills: { supersmash_solo_kills: 15 },
  supersmash_solo_win: { supersmash_solo_win: 1 },
  supersmash_team_kills: { supersmash_team_kills: 15 },
  supersmash_team_win: { supersmash_team_win: 1 },
  supersmash_weekly_kills: { supersmash_weekly_kills: 150 },
  team_brawler: {},
  tnt_bowspleef_daily: { tnt_bowspleef_daily: 40 },
  tnt_bowspleef_weekly: { tnt_bowspleef_weekly: 200 },
  tnt_daily_win: { tnt_daily_win: 1 },
  tnt_pvprun_daily: { tnt_pvprun_daily: 3 },
  tnt_pvprun_weekly: { tnt_pvprun_weekly: 25 },
  tnt_tntrun_daily: { tnt_tntrun_daily: 500 },
  tnt_tntrun_weekly: { tnt_tntrun_weekly: 2000 },
  tnt_tnttag_daily: { tnt_tnttag_daily: 7 },
  tnt_tnttag_weekly: { tnt_tnttag_weekly: 50 },
  tnt_weekly_play: { tnt_weekly_play: 20 },
  tnt_wizards_daily: { tnt_wizards_daily_kills: 10 },
  tnt_wizards_weekly: { tnt_wizards_weekly_kills: 150 },
  uhc_dm: { uhc_kills: 2 },
  uhc_madness: { kill: 100 },
  uhc_solo: { uhc_kills: 1 },
  uhc_team: { uhc_kills: 1 },
  uhc_weekly: { uhc_kills: 20 },
  vampirez_daily_human_kill: { vampirez_daily_kill_human: 10 },
  vampirez_daily_kill: { vampirez_daily_kill_vampire: 10, vampirez_daily_kill_zombie: 20 },
  vampirez_daily_play: { vampirez_daily_play: 1 },
  vampirez_daily_win: { vampirez_daily_win: 1 },
  vampirez_weekly_human_kill: { vampirez_weekly_kill_survivor: 100 },
  vampirez_weekly_kill: { vampirez_weekly_kill_zombie: 130, vampirez_weekly_kill_vampire: 25 },
  vampirez_weekly_win: { vampirez_weekly_win_survivor: 12 },
  walls_daily_kill: { walls_daily_kill: 5 },
  walls_daily_play: { walls_daily_play: 1 },
  walls_daily_win: { walls_daily_win: 1 },
  walls_weekly: { walls_weekly_play: 7, walls_weekly_kills: 25 },
  warlords_all_star: { warlords_weekly_damage: 1_500_000, warlords_weekly_heal: 1_500_000 },
  warlords_ctf: {},
  warlords_dedication: { warlords_weekly_dedi: 20 },
  warlords_domination: {},
  warlords_objectives: { warlords_daily_objectives: 100 },
  warlords_tdm: {},
  warlords_victorious: {},
  wool_wars_daily_kills: { kill: 20 },
  wool_wars_daily_play: { play: 1 },
  wool_wars_daily_wins: { win: 3 },
  wool_wars_weekly_shears: { wool_weekly_shears: 200 },
  wool_weekly_play: { win: 15, kill: 100 },
};
