pull_request_title: 'chore(i18n): update crowdin translation'
commit_message: 'chore(i18n): update translations for `%language%`'
append_commit_message: 
files:
  - source: /locales/en-US/default.json
    translation: /locales/%locale%/%original_file_name%
