packages:
  - apps/**
  - packages/**
  - assets/**

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@sentry-internal/node-cpu-profiler'
  - '@scarf/scarf'
  - '@swc/core'
  - esbuild
  - sharp
  - skia-canvas
  - unrs-resolver
