packages:
  - apps/**
  - packages/**
  - "!packages/skin-renderer/pkg"
  - assets/**

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@scarf/scarf'
  - '@swc/core'
  - esbuild
  - sharp
  - skia-canvas
  - unrs-resolver
