packages:
  - apps/**
  - packages/**
  - assets/**
allowBuilds:
  '@nestjs/core': true
  '@scarf/scarf': true
  '@swc/core': true
  esbuild: true
  sharp: true
  skia-canvas: true
  unrs-resolver: true
