export const minecraftColors = [
  { code: '§0', hex: '#000000', id: 'BLACK' },
  { code: '§1', hex: '#0000AA', id: 'DARK_BLUE' },
  { code: '§2', hex: '#00AA00', id: 'DARK_GREEN' },
  { code: '§3', hex: '#00AAAA', id: 'DARK_AQUA' },
  { code: '§4', hex: '#AA0000', id: 'DARK_RED' },
  { code: '§5', hex: '#AA00AA', id: 'DARK_PURPLE' },
  { code: '§6', hex: '#FFAA00', id: 'GOLD' },
  { code: '§7', hex: '#BAB6B6', id: 'GRAY' },
  { code: '§8', hex: '#555555', id: 'DARK_GRAY' },
  { code: '§9', hex: '#5555FF', id: 'BLUE' },
  { code: '§a', hex: '#55FF55', id: 'GREEN' },
  { code: '§b', hex: '#55FFFF', id: 'AQUA' },
  { code: '§c', hex: '#FF5555', id: 'RED' },
  { code: '§d', hex: '#FF55FF', id: 'LIGHT_PURPLE' },
  { code: '§e', hex: '#FFFF55', id: 'YELLOW' },
  { code: '§f', hex: '#F2F2F2', id: 'WHITE' },
];
