name: Bug report
description: Report incorrect or unexpected behavior
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Use the Discord and proper channels for questions and support: https://statsify.net/discord
  - type: dropdown
    id: package
    attributes:
      label: Which package is this bug report for?
      multiple: true
      options:
        - api
        - discord-bot
        - site
        - "@statsify/assets"
        - "@statsify/discord"
        - "@statsify/jsx"
        - "@statsify/logger"
        - "@statsify/math"
        - "@statsify/schemas"
        - "@statsify/util"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Issue description
      description: |
        Describe the issue in as much detail as possible.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files into it.
      placeholder: |
        This and this is wrong because [...]. You can reproduce the issue by doing x, y, and z
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating system
      description: What OS do you run? Have you tried recreating it on other systems?