name: Feature request
description: Suggest an idea for this project
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: dropdown
    id: package
    attributes:
      label: Which package is the feature request for?
      options:
        - api
        - discord-bot
        - site
        - discord
        - logger
        - math
        - schemas
        - util
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Feature
      description: A clear and concise description of what the problem is, or what feature you want to be implemented.
      placeholder: I'm always frustrated when [...], Hypixel added [...]
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Ideal solution or implementation
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative solutions or implementations
      description: A clear and concise description of any alternative solutions or features you have considered.
  - type: textarea
    id: additional-context
    attributes:
      label: Other context
      description: Any other context, screenshots, or file uploads that help us understand your feature request.