/**
 * Copyright (c) Statsify
 *
 * This source code is licensed under the GNU GPL v3 license found in the
 * LICENSE file in the root directory of this source tree.
 * https://github.com/Statsify/statsify/blob/main/LICENSE
 */

import Image from "next/image";
import { Inter } from "next/font/google";
import { Navbar } from "~/components/navbar";
import "./globals.css";
import type { Metadata } from "next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Statsify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col`}>
        <Image src="/backgrounds/hypixel_overall_2.png" alt="background" fill className="z-[-5] blur-lg absolute brightness-75" />
        <Navbar className="absolute" />
        <main className="w-full p-[2%] flex flex-col items-center justify-center grow">
          {children}
        </main>
      </body>
    </html>
  );
}
