[package]
name = "statsify-skin-renderer"
authors = ["Jacob Koshy <jababakoshy@gmail.com>"]
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
bytemuck = { version = "1.23.0", features = ["derive"] }
cgmath = "0.18.0"
futures-intrusive = "0.5.0"
image = "0.25.6"
thiserror = "2.0.12"
cfg-if = "1.0.0"
strum = { version = "0.27.1", features = ["derive"] }
tracing = "0.1.41"
once_cell = "1.21.3"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wgpu = { version = "26.0.1", features = ["webgl"] }
wasm-bindgen = "0.2.100"
wasm-bindgen-futures = "0.4.50"
web-sys = { version = "0.3.77", features = ["Document", "Window", "Element", "HtmlCanvasElement"] }
winit = "0.30"
console_error_panic_hook = "0.1.7"
console_log = "1.0"
futures-channel = "0.3.31"
tracing-wasm = "0.2.1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1.45.1", features = ["full"] }
lazy_static = "1.5.0"
async_once = "0.2.6"
napi = { version = "3.2.4", features = ["async"] }
napi-derive = "3.2.4"
wgpu = "26.0.1"

[build-dependencies]
napi-build = "2.2.0"
