[package]
name = "statsify-skin-renderer"
authors = ["Jacob Koshy <jababakoshy@gmail.com>"]
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
bytemuck = { version = "1.13.1", features = ["derive"] }
cgmath = "0.18.0"
futures-intrusive = "0.5.0"
image = "0.24.7"
thiserror = "1.0.48"
cfg-if = "1.0.0"
strum = { version = "0.26.1", features = ["derive"] }
tracing = "0.1.40"
once_cell = "1.19.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wgpu = { version = "0.18", features = ["webgl"] }
wasm-bindgen = "0.2.89"
wasm-bindgen-futures = "0.4.39"
web-sys = { version = "0.3.6", features = ["Document", "Window", "Element"] }
winit = "0.28"
console_error_panic_hook = "0.1"
console_log = "1.0"
futures-channel = "0.3.30"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1.32.0", features = ["full"] }
lazy_static = "1.4.0"
async_once = "0.2.6"
napi = { version = "2.16.5", features = ["async"] }
napi-derive = "2.16.5"
wgpu = "0.18.0"

[build-dependencies]
napi-build = "2.1.3"