[package]
name    = "statsify-skin-renderer"
authors = ["Jacob Koshy <jababakoshy@gmail.com>"]
edition = "2021"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2.13.2", features = ["async"] }
napi-derive = "2.13.0"
bytemuck = { version = "1.13.1", features = ["derive"] }
cgmath = "0.18.0"
futures-intrusive = "0.5.0"
image = "0.24.6"
png = "0.17.7"
tobj = { version = "4.0.0", features = ["async"] }
wgpu = "0.17.0"
thiserror = "1.0.40"
tokio = { version = "1.27.0", features = ["full"] }
lazy_static = "1.4.0"
async_once = "0.2.6"
reqwest = "0.11.18"

[build-dependencies]
napi-build = "2.0.1"
fs_extra = "1.2.0"
glob = "0.3.0"