/**
 * Copyright (c) Statsify
 *
 * This source code is licensed under the GNU GPL v3 license found in the
 * LICENSE file in the root directory of this source tree.
 * https://github.com/Statsify/statsify/blob/main/LICENSE
 */

/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function renderSkin(skinUrl: string | undefined | null, isSlim: boolean): Promise<Buffer>
