/**
 * Copyright (c) Statsify
 *
 * This source code is licensed under the GNU GPL v3 license found in the
 * LICENSE file in the root directory of this source tree.
 * https://github.com/Statsify/statsify/blob/main/LICENSE
 */

import { Background } from "~/components/background";
import { Navbar } from "~/components/navbar";
import type { Metadata } from "next";
import type { PropsWithChildren } from "react";

export const metadata: Metadata = {
	title: "Statsify",
	description: "Generated by create next app",
};

export default function Layout({ children }: PropsWithChildren) {
	return (
		<>
			<Background />
			<Navbar />
			{children}
		</>
	);
}
