/**
 * Copyright (c) Statsify
 *
 * This source code is licensed under the GNU GPL v3 license found in the
 * LICENSE file in the root directory of this source tree.
 * https://github.com/Statsify/statsify/blob/main/LICENSE
 */

export type HypixelLobby =
  | "Adventure"
  | "ArcadeGames"
  | "Arena"
  | "Bedwars"
  | "BlitzLobby"
  | "BuildBattle"
  | "CopsnCrims"
  | "Duels"
  | "Housing"
  | "Legacy"
  | "MainLobby"
  | "MegaWalls"
  | "MurderMystery"
  | "NewMainLobby"
  | "Paintball"
  | "Prototype"
  | "QuakeCraft"
  | "SC"
  | "SkyClash"
  | "Skywars"
  | "SkywarsAug2017"
  | "SkywarsChristmas2017"
  | "SkywarsStandard2022"
  | "SpeedUHC"
  | "SuperSmash"
  | "TNT"
  | "TheWallsLobby"
  | "Tourney"
  | "TruePVPParkour"
  | "Turbo"
  | "Warlords"
  | "WoolGames"
  | "blitz"
  | "bossfight"
  | "christmas"
  | "main"
  | "mainLobby2017"
  | "mainLobby2022"
  | "megawallslobby"
  | "newwalls"
  | "overhaul"
  | "quakelobby"
  | "uhc"
  | "vampirez";

export type HypixelGameMode =
  | "Arcade"
  | "Arena"
  | "Battleground"
  | "Bedwars"
  | "BuildBattle"
  | "Duels"
  | "GingerBread"
  | "Housing"
  | "HungerGames"
  | "Legacy"
  | "MCGO"
  | "MurderMystery"
  | "Paintball"
  | "Pit"
  | "Quake"
  | "SkyClash"
  | "SkyWars"
  | "SpeedUHC"
  | "SuperSmash"
  | "TNTGames"
  | "TrueCombat"
  | "UHC"
  | "VampireZ"
  | "Walls"
  | "Walls3"
  | "WoolGames";

export type HypixelAchievementMode =
  | "arcade"
  | "arena"
  | "bedwars"
  | "blitz"
  | "buildbattle"
  | "christmas2017"
  | "copsandcrims"
  | "duels"
  | "easter"
  | "general"
  | "gingerbread"
  | "halloween2017"
  | "housing"
  | "murdermystery"
  | "paintball"
  | "pit"
  | "quake"
  | "skyblock"
  | "skyclash"
  | "skywars"
  | "speeduhc"
  | "summer"
  | "supersmash"
  | "tntgames"
  | "truecombat"
  | "uhc"
  | "vampirez"
  | "walls"
  | "walls3"
  | "warlords"
  | "woolgames";
