import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

export const metadata: Metadata = {
  title: "Statsify",
  description: "Generated by create next app",
};


const MinecraftFont = localFont({
  src: [
    { style: "Regular", weight: "400", path: "./fonts/Minecraft.ttf" },
    { style: "Bold", weight: "600", path: "./fonts/Minecraft Bold.ttf" },
    { style: "Italic", weight: "400", path: "./fonts/Minecraft Italic.ttf" },
    { style: "Italic", weight: "600", path: "./fonts/Minecraft Bold Italic.ttf" },
  ],
  preload:true,
  variable: "--font-minecraft",
});


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${MinecraftFont.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
