/**
 * Copyright (c) Statsify
 *
 * This source code is licensed under the GNU GPL v3 license found in the
 * LICENSE file in the root directory of this source tree.
 * https://github.com/Statsify/statsify/blob/main/LICENSE
 */

import localFont from "next/font/local";
import { Footer } from "~/components/ui/footer";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Statsify",
  description: "Generated by create next app",
};

const MinecraftFont = localFont({
  src: [
    { style: "Regular", weight: "400", path: "./fonts/Minecraft.ttf" },
    { style: "Bold", weight: "600", path: "./fonts/Minecraft Bold.ttf" },
    { style: "Italic", weight: "400", path: "./fonts/Minecraft Italic.ttf" },
    { style: "Italic", weight: "600", path: "./fonts/Minecraft Bold Italic.ttf" },
  ],
  preload: true,
  variable: "--font-minecraft",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${MinecraftFont.variable} antialiased leading-[normal]`}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
