name: Lint

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  # Replace pull_request with pull_request_target if you
  # plan to use this action with forks, see the Limitations section
  pull_request:
    branches:
      - main

# Down scope as necessary via https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
permissions:
  checks: write
  contents: write

jobs:
  lint:
    name: Lint
    strategy:
      matrix:
        package: ["apps/api", "apps/discord-bot", "apps/scripts", "apps/verify-server", "packages/api-client", "packages/assets", "packages/discord", "packages/logger", "packages/math", "packages/rendering", "packages/schemas", "packages/util"]
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install node.js v16
        uses: actions/setup-node@eeb10cff27034e7acf239c5d29f62154018672fd # tag=v3
        with:
          node-version: 16
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      # Install your linters here
      - name: Install dependencies
        uses: yarn --immutable

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          eslint_dir: ${{ matrix.package }}/{src,tests}/**/*
          eslint_extensions: js,jsx,ts,tsx,cjs,mjs,cts,mts,json